# Generated by Django 2.1.3 on 2018-11-19 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('profesor', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.CharField(max_length=250)),
                ('nombre_programa', models.CharField(max_length=250)),
                ('grado', models.CharField(max_length=250)),
                ('anio', models.IntegerField()),
                ('cursos', models.ManyToManyField(through='final.Asignacion', to='final.Curso')),
            ],
        ),
        migrations.AddField(
            model_name='asignacion',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final.Curso'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final.Programa'),
        ),
    ]
